node {

    stage ('Code checkout'){
    	checkout scm
    }

    docker.withTool('dockerTool'){
        withDockerServer([uri: 'tcp://docker-in-docker:2375']) {
	    stage('Testing') {
		    /* 
		 docker.image('nginx').run()
		   

	         docker.image('maven:3.5-jdk-7-alpine').withRun() {
		      sh 'mvn --version'
		 } 
		 */
		 docker.image('maven:3.5-jdk-7-alpine').inside("-u 501") {
		      sh 'mvn --version'
		 } 
		    /*
	         docker.image('maven:3.5-jdk-7-alpine').inside {
		      sh 'mvn -f apps/helloworld-ws/pom.xml pre-integration-test'
		} 

	         docker.image('maven:3.5-jdk-8-alpine').inside {
		      sh 'mvn -f apps/helloworld-ws/pom.xml integration-test'
		} 
		*/
	    }
		/*
            stage ('Building'){
	       docker.image('maven:3.5-jdk-7-alpine').inside {
	          sh 'mvn -f apps/pom.xml install'
	      }
           }
	   */
       }
    }
}
